CREATE DATABASE SALES_DB;

CREATE SCHEMA SALES_DB.SALES_SCHEMA;

SHOW SCHEMAS IN DATABASE SALES_DB;

CREATE TABLE SALES_DB.SALES_SCHEMA.CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    ADDRESS VARCHAR
);

SHOW TABLES IN SALES_DB.SALES_SCHEMA;

CREATE TABLE SALES_DB.SALES_SCHEMA.ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT FLOAT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES SALES_DB.SALES_SCHEMA.CUSTOMERS(CUSTOMER_ID)
);

SHOW TABLES IN SALES_DB.SALES_SCHEMA;